### ISSUE TITLE
Table escape sequences are ignored and formatted

### ISSUE THREAD

**Issue by sftblw** [ClareKang/Gaji#1]
`\|` should be ignored when It is inside of table but it is formatted as border bar.

```
시나리오:
    조건
       예:
| cell a | cell b |
|   \|   |        |
```

formats to

```
시나리오:

   조건

       예:
           |cell a|cell b|
           |   \  |      |
```

**Comment by clarekang** [comment]
Okay. I'll find out.

**Comment by clarekang** [comment]
@sftblw 
Hi, It 's too late for your question.
I think the problem you are having is not a bug.
Just use an empty value with `\` instead of `\|`.
Or are there other problems?

Anyway, I fixed the problem you issue raised.
If you write the following code and use as follow
```
시나리오: 시나리오이다
조건 <cell a>는 <cell b>이다
예:
|cell a|cell b|
|\||어떤값|
```
It will be formatted like this.
```
시나리오: 시나리오이다

   조건 <cell a>는 <cell b>이다

       예:
           |cell a|cell b|
           |  \|  |어떤값|
```
